"""second  Migration

Revision ID: 0be7b2a8d123
Revises: c10655166c64
Create Date: 2019-10-01 16:55:24.250625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be7b2a8d123'
down_revision = 'c10655166c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('comments_blogger_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'blogger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blogger_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_blogger_id_fkey', 'comments', 'blogger', ['blogger_id'], ['id'])
    op.drop_table('subscribe')
    # ### end Alembic commands ###
